Update GH Action
bellshade/bellshade-monorepo pull request #30
Opened 2022-03-24 19:48 UTC by nuraskiah

## Environment

Saya menggunakan:

- `os` = `Linux`

## Daftar Tugas

- [x] Memperbaiki github action untuk deploy server karena nama repositorinya berbeda

2022-03-25 03:24 UTC, nomadkode approved these changes

2022-03-25 06:45 UTC, reacto11mecha requested changes
Oiya mbak, aman gak kalo ada lock filenya ? Soalnya kalo ga ada lockfile ga bisa di publish, saran ku coba jalanin `git checkout .` abis nge install packagenya

2022-03-25 06:45 UTC, reacto11mecha commented on .github/workflows/cd.yml
> +    branches: [main]
Dibikin folder tertentu aja mba biar semisa ada update di ningali yang jalan publishernya aja

```suggestion
    branches: [main]
    paths:
    - 'packages/server/**'
    - 'packages/shared/**'
  pull_request:
    types: [closed]
    branches: [main]
    paths:
    - 'packages/server/**'
    - 'packages/shared/**'
```

2022-03-28 04:45 UTC, reacto11mecha commented
Mba @nuraskiah ada update ?

2022-03-28 05:00 UTC, nuraskiah commented
sorry. updated zra

2022-03-28 05:11 UTC, nuraskiah commented
> Oiya mbak, aman gak kalo ada lock filenya ? Soalnya kalo ga ada lockfile ga bisa di publish, saran ku coba jalanin `git checkout .` abis nge install packagenya

updated zra, `git checkout .` udah kutambahin sblm `git pull` biar ga conflict

2022-03-28 06:31 UTC, reacto11mecha approved these changes
Sip mba, LGTM :+1:

2022-03-28 06:31 UTC, merged